apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: default  # Specify the default namespace here
spec:
  replicas: 3  # Number of pod replicas
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: nginx:latest  # Replace with your container image
        ports:
        - containerPort: 80
